### PR TITLE
Fix EINVAL crash

### PR DESCRIPTION
**Pull request by addison-adler**
Related Issues:
- [EINVAL crash on latest nodejs](https://github.com/rokucommunity/ropm/issues/77)

> There's a weird crash with the latest version of NodeJS when running ropm.

```$ ropm install roku-requests
Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:760:9)
    at C:\Users\bronley\AppData\Roaming\npm\node_modules\ropm\dist\util.js:24:40
    at new Promise (<anonymous>)
    at Util.spawnAsync (C:\Users\bronley\AppData\Roaming\npm\node_modules\ropm\dist\util.js:23:16)
    at Util.spawnNpmAsync (C:\Users\bronley\AppData\Roaming\npm\node_modules\ropm\dist\util.js:37:21)
    at InstallCommand.npmInstall (C:\Users\bronley\AppData\Roaming\npm\node_modules\ropm\dist\commands\InstallCommand.js:70:27)
    at async InstallCommand.run (C:\Users\bronley\AppData\Roaming\npm\node_modules\ropm\dist\commands\InstallCommand.js:39:13) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
} ```

Adding `shell: true` fixes the crash

### CODE REVIEW

**Comment by TwitchBronBron** [comment]
I THINK I remember seeing this option also pop open an actual shell popup. But there's another option for  show: false. Could you check into that and report back?

**Comment by addison-adler** [comment]
> I THINK I remember seeing this option also pop open an actual shell popup. But there's another option for show: false. Could you check into that and report back?
> 
> I'd prefer to hide the popup shell if possible..

There is another option we can add for this: `windowsHide`
`Hide the subprocess console window that would normally be created on Windows systems.`

**Comment by addison-adler** [comment]
... and I have just learned that there are unit tests related to this.. I'll update those 😄

**Review by TwitchBronBron — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
